### ISSUE TITLE
Not working for jHipster 8.0.0

### ISSUE THREAD

**Issue by dave0688** [jhipster/generator-jhipster-entity-audit#200]
Hi,

first of al thanks for the great work in this package - we really like it in our project!
However, we just upgraded to jHipster 8.0.0.beta-1 (yep, the beta :D) and it throws an error that it's not compatible with jHipster 8.0.0. 

Is there any plan to migrate it yet? No pressure, just asking for a timeline :)

**Comment by dave0688** [comment]
Can someone please give a message about the plans when to migrate it? We would love to keep using the audits - it's a very cool feature :)

**Comment by skippedaga** [comment]
Can I help to fix the issue? 

node:internal/modules/cjs/loader:573
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/util/namespace' is not defined by "exports" in C:\Users\skipp\AppData\Local\npm-cache\_npx\733ef9826afea744\node_modules\yeoman-environment\package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:359:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:695:9)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\skipp\AppData\Local\npm-cache\_npx\733ef9826afea744\node_modules\generator-jhipster\utils\blueprint.js:19:25) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

**Comment by sw-enthusiast** [comment]
I am running into this error when I tried to install it thru the JDL. Help with the workaround would be greatly appreciated. 

`ERROR! An error occured while running jhipster:bootstrap#validateBlueprint
ERROR! ERROR! The installed generator-jhipster-entity-audit blueprint targets JHipster v7.9.3 and is not compatible with this JHipster version. Either update the blueprint or JHipster. You can also disable this check using --skip-checks at your own risk
Error: The installed generator-jhipster-entity-audit blueprint targets JHipster v7.9.3 and is not compatible with this JHipster version. Either update the blueprint or JHipster. You can also disable this check using --skip-checks at your own risk
    at BootstrapGenerator._checkJHipsterBlueprintVersion (file:///C:/Users/test/AppData/Roaming/npm/node_modules/generator-jhipster/dist/generators/base/generator-base-blueprint.mjs:516:19)
    at file:///C:/Users/test/AppData/Roaming/npm/node_modules/generator-jhipster/dist/generators/bootstrap/generator.mjs:57:30
    at Array.forEach (<anonymous>)
    at BootstrapGenerator.validateBlueprint (file:///C:/Users/test/AppData/Roaming/npm/node_modules/generator-jhipster/dist/generators/bootstrap/generator.mjs:56:52)
    at BootstrapGenerator.executeTask (file:///C:/Users/test/AppData/Roaming/npm/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:240:26)
    at env.queueTask.once (file:///C:/Users/test/AppData/Roaming/npm/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:214:56)
    at runLoop.add.once (file:///C:/Users/test/AppData/Roaming/npm/node_modules/generator-jhipster/node_modules/yeoman-environment/dist/environment-base.js:383:23)
    at Immediate.<anonymous> (C:\Users\test\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\grouped-queue\lib\subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:476:21)`
